window.HSK_VOCAB = {
  1: [
    { hanzi: "爱", pinyin: "ai4", meaning: "사랑하다" },
    { hanzi: "八", pinyin: "ba1", meaning: "여덟" },
    { hanzi: "爸爸", pinyin: "ba4 ba", meaning: "아빠" },
    { hanzi: "北京", pinyin: "bei3 jing1", meaning: "베이징" },
    { hanzi: "本", pinyin: "ben3", meaning: "권, 책의 단위" },
    { hanzi: "不客气", pinyin: "bu2 ke4 qi", meaning: "천만에요" },
    { hanzi: "菜", pinyin: "cai4", meaning: "요리, 반찬" },
    { hanzi: "茶", pinyin: "cha2", meaning: "차" },
    { hanzi: "吃", pinyin: "chi1", meaning: "먹다" },
    { hanzi: "出租车", pinyin: "chu1 zu1 che1", meaning: "택시" },
    { hanzi: "打电话", pinyin: "da3 dian4 hua4", meaning: "전화하다" },
    { hanzi: "大学", pinyin: "da4 xue2", meaning: "대학교" },
    { hanzi: "电脑", pinyin: "dian4 nao3", meaning: "컴퓨터" },
    { hanzi: "对不起", pinyin: "dui4 bu qi3", meaning: "미안합니다" },
    { hanzi: "多", pinyin: "duo1", meaning: "많다" },
    { hanzi: "儿子", pinyin: "er2 zi", meaning: "아들" },
    { hanzi: "饭店", pinyin: "fan4 dian4", meaning: "식당" },
    { hanzi: "高兴", pinyin: "gao1 xing4", meaning: "기쁘다" },
    { hanzi: "喝", pinyin: "he1", meaning: "마시다" },
    { hanzi: "今天", pinyin: "jin1 tian1", meaning: "오늘" }
  ],
  2: [
    { hanzi: "帮助", pinyin: "bang1 zhu4", meaning: "돕다" },
    { hanzi: "比赛", pinyin: "bi3 sai4", meaning: "경기, 시합" },
    { hanzi: "别", pinyin: "bie2", meaning: "하지 마라, 다른" },
    { hanzi: "城市", pinyin: "cheng2 shi4", meaning: "도시" },
    { hanzi: "唱歌", pinyin: "chang4 ge1", meaning: "노래하다" },
    { hanzi: "穿", pinyin: "chuan1", meaning: "입다, 신다" },
    { hanzi: "错", pinyin: "cuo4", meaning: "틀리다, 잘못" },
    { hanzi: "附近", pinyin: "fu4 jin4", meaning: "근처" },
    { hanzi: "感冒", pinyin: "gan3 mao4", meaning: "감기" },
    { hanzi: "给", pinyin: "gei3", meaning: "주다" },
    { hanzi: "公共汽车", pinyin: "gong1 gong4 qi4 che1", meaning: "버스" },
    { hanzi: "黑", pinyin: "hei1", meaning: "검다" },
    { hanzi: "欢迎", pinyin: "huan1 ying2", meaning: "환영하다" },
    { hanzi: "教室", pinyin: "jiao4 shi4", meaning: "교실" },
    { hanzi: "开始", pinyin: "kai1 shi3", meaning: "시작하다" },
    { hanzi: "考试", pinyin: "kao3 shi4", meaning: "시험" },
    { hanzi: "旅行", pinyin: "lu:3 xing2", meaning: "여행" },
    { hanzi: "慢", pinyin: "man4", meaning: "느리다" },
    { hanzi: "牛奶", pinyin: "niu2 nai3", meaning: "우유" },
    { hanzi: "希望", pinyin: "xi1 wang4", meaning: "희망하다" }
  ],
  3: [
    { hanzi: "成绩", pinyin: "cheng2 ji4", meaning: "성적, 결과" },
    { hanzi: "聪明", pinyin: "cong1 ming", meaning: "똑똑하다" },
    { hanzi: "打扫", pinyin: "da3 sao3", meaning: "청소하다" },
    { hanzi: "锻炼", pinyin: "duan4 lian4", meaning: "운동하다" },
    { hanzi: "发烧", pinyin: "fa1 shao1", meaning: "열이 나다" },
    { hanzi: "发现", pinyin: "fa1 xian4", meaning: "발견하다" },
    { hanzi: "方便", pinyin: "fang1 bian4", meaning: "편리하다" },
    { hanzi: "干净", pinyin: "gan1 jing4", meaning: "깨끗하다" },
    { hanzi: "管理", pinyin: "guan3 li3", meaning: "관리하다" },
    { hanzi: "河", pinyin: "he2", meaning: "강" },
    { hanzi: "会议", pinyin: "hui4 yi4", meaning: "회의" },
    { hanzi: "机会", pinyin: "ji1 hui4", meaning: "기회" },
    { hanzi: "简单", pinyin: "jian3 dan1", meaning: "간단하다" },
    { hanzi: "决定", pinyin: "jue2 ding4", meaning: "결정하다" },
    { hanzi: "练习", pinyin: "lian4 xi2", meaning: "연습하다" },
    { hanzi: "努力", pinyin: "nu3 li4", meaning: "노력하다" },
    { hanzi: "其他", pinyin: "qi2 ta1", meaning: "기타, 다른" },
    { hanzi: "突然", pinyin: "tu1 ran2", meaning: "갑자기" },
    { hanzi: "忘记", pinyin: "wang4 ji4", meaning: "잊다" },
    { hanzi: "重要", pinyin: "zhong4 yao4", meaning: "중요하다" }
  ],
  4: [
    { hanzi: "安排", pinyin: "an1 pai2", meaning: "안배하다, 계획하다" },
    { hanzi: "表演", pinyin: "biao3 yan3", meaning: "공연하다" },
    { hanzi: "毕业", pinyin: "bi4 ye4", meaning: "졸업하다" },
    { hanzi: "成功", pinyin: "cheng2 gong1", meaning: "성공하다" },
    { hanzi: "打扮", pinyin: "da3 ban4", meaning: "꾸미다" },
    { hanzi: "堵车", pinyin: "du3 che1", meaning: "교통 체증" },
    { hanzi: "翻译", pinyin: "fan1 yi4", meaning: "번역하다" },
    { hanzi: "丰富", pinyin: "feng1 fu4", meaning: "풍부하다" },
    { hanzi: "工资", pinyin: "gong1 zi1", meaning: "월급" },
    { hanzi: "海洋", pinyin: "hai3 yang2", meaning: "바다, 해양" },
    { hanzi: "激动", pinyin: "ji1 dong4", meaning: "감동하다, 흥분하다" },
    { hanzi: "坚持", pinyin: "jian1 chi2", meaning: "견지하다" },
    { hanzi: "拒绝", pinyin: "ju4 jue2", meaning: "거절하다" },
    { hanzi: "考虑", pinyin: "kao3 lu:4", meaning: "고려하다" },
    { hanzi: "联系", pinyin: "lian2 xi4", meaning: "연락하다" },
    { hanzi: "耐心", pinyin: "nai4 xin1", meaning: "인내심" },
    { hanzi: "批评", pinyin: "pi1 ping2", meaning: "비판하다" },
    { hanzi: "适合", pinyin: "shi4 he2", meaning: "적합하다" },
    { hanzi: "提高", pinyin: "ti2 gao1", meaning: "향상시키다" },
    { hanzi: "选择", pinyin: "xuan3 ze2", meaning: "선택하다" }
  ],
  5: [
    { hanzi: "保持", pinyin: "bao3 chi2", meaning: "유지하다" },
    { hanzi: "辩论", pinyin: "bian4 lun4", meaning: "토론하다" },
    { hanzi: "创新", pinyin: "chuang4 xin1", meaning: "혁신" },
    { hanzi: "独立", pinyin: "du2 li4", meaning: "독립적이다" },
    { hanzi: "发表", pinyin: "fa1 biao3", meaning: "발표하다" },
    { hanzi: "合理", pinyin: "he2 li3", meaning: "합리적이다" },
    { hanzi: "忽视", pinyin: "hu1 shi4", meaning: "무시하다" },
    { hanzi: "技术", pinyin: "ji4 shu4", meaning: "기술" },
    { hanzi: "减少", pinyin: "jian3 shao3", meaning: "줄이다" },
    { hanzi: "经历", pinyin: "jing1 li4", meaning: "경험, 겪다" },
    { hanzi: "明确", pinyin: "ming2 que4", meaning: "명확하다" },
    { hanzi: "判断", pinyin: "pan4 duan4", meaning: "판단하다" },
    { hanzi: "签证", pinyin: "qian1 zheng4", meaning: "비자" },
    { hanzi: "熟悉", pinyin: "shu2 xi1", meaning: "익숙하다" },
    { hanzi: "投入", pinyin: "tou2 ru4", meaning: "투입하다" },
    { hanzi: "效率", pinyin: "xiao4 lu:4", meaning: "효율" },
    { hanzi: "形成", pinyin: "xing2 cheng2", meaning: "형성하다" },
    { hanzi: "压力", pinyin: "ya1 li4", meaning: "압력, 스트레스" },
    { hanzi: "责任", pinyin: "ze2 ren4", meaning: "책임" },
    { hanzi: "准确", pinyin: "zhun3 que4", meaning: "정확하다" }
  ],
  6: [
    { hanzi: "摆脱", pinyin: "bai3 tuo1", meaning: "벗어나다" },
    { hanzi: "比如", pinyin: "bi3 ru2", meaning: "예를 들면" },
    { hanzi: "采取", pinyin: "cai3 qu3", meaning: "채택하다, 취하다" },
    { hanzi: "承受", pinyin: "cheng2 shou4", meaning: "견디다" },
    { hanzi: "概括", pinyin: "gai4 kuo4", meaning: "개괄하다" },
    { hanzi: "贡献", pinyin: "gong4 xian4", meaning: "기여하다" },
    { hanzi: "缓解", pinyin: "huan3 jie3", meaning: "완화하다" },
    { hanzi: "计算", pinyin: "ji4 suan4", meaning: "계산하다" },
    { hanzi: "建立", pinyin: "jian4 li4", meaning: "세우다, 설립하다" },
    { hanzi: "接触", pinyin: "jie1 chu4", meaning: "접촉하다" },
    { hanzi: "理论", pinyin: "li3 lun4", meaning: "이론" },
    { hanzi: "明确", pinyin: "ming2 que4", meaning: "분명히 하다" },
    { hanzi: "批准", pinyin: "pi1 zhun3", meaning: "승인하다" },
    { hanzi: "趋势", pinyin: "qu1 shi4", meaning: "추세" },
    { hanzi: "实施", pinyin: "shi2 shi1", meaning: "실시하다" },
    { hanzi: "调节", pinyin: "tiao2 jie2", meaning: "조절하다" },
    { hanzi: "围绕", pinyin: "wei2 rao4", meaning: "둘러싸다, 중심으로 하다" },
    { hanzi: "形成", pinyin: "xing2 cheng2", meaning: "형성하다" },
    { hanzi: "意识", pinyin: "yi4 shi", meaning: "의식" },
    { hanzi: "支持", pinyin: "zhi1 chi2", meaning: "지지하다" }
  ]
};
